# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 3

workflows:
  build-and-deploy:
    jobs:
      - build:
        context:
          - dockerhub
jobs:
  build:
    docker:
      - image: cimg/base

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Build and deploy docker image
          command: |
            echo $DOCKER_ACCESS_TOKEN | docker login --username $DOCKER_USER --password-stdin

            # build docker image
            docker build -t zackmattor/zack-mattor:latest .
            docker tag zackmattor/zack-mattor:latest zackmattor/zack-mattor:$CIRCLE_SHA1
            docker push zackmattor/zack-mattor:$CIRCLE_SHA1
            docker push zackmattor/zack-mattor:latest
